### ISSUE TITLE
bilibili插件添加后内发送指令没反应

### ISSUE THREAD

**Issue by Fui-Reconk** [Zeta-qixi/nonebot2-plugins#10]
没有任何报错提示，只有接收成功的消息反馈（是在其他机器人上魔改的）
![image](https://user-images.githubusercontent.com/109668834/180116175-c4bd4c2d-0c15-41e3-85d5-a34d75bb4ab3.png)

**Comment by Zeta-qixi** [comment]
看看有没有加载成功（nb启动时的输出）

**Comment by Fui-Reconk** [comment]
![image](https://user-images.githubusercontent.com/109668834/180118773-6795705a-94d6-47bc-8751-1e8769ed29fb.png)
应该成功的吧

**Comment by Zeta-qixi** [comment]
测试了一下 通过了，是不是你的bot有命令前缀？ 或者是被其它插件block了？
试试在添加关注的方法里log点东西，看看有没有触发。

**Comment by Fui-Reconk** [comment]
emmmm...具体操作有点不会,,,但把其他插件全移除后还是没有反应

**Comment by Zeta-qixi** [comment]
`live`的`__init__.py` 51行后 添加 logger.info()

如下
```
add_up = on_command('添加关注', block= True)
@add_up.handle()
async def add(bot: Bot, event: MessageEvent, state: T_State, mid: Message = CommandArg()):
    logger.info("test")   # 添加这一行

```

我感觉你是有命令前缀 试试`/添加关注 xxxxxx`

**Comment by Fui-Reconk** [comment]
确实有命令前缀，解决了谢谢啦

**Comment by Fui-Reconk** [comment]
emmm这里判断是不是有点问题
![image](https://user-images.githubusercontent.com/109668834/180124841-ac3bfa08-16ff-4ceb-82b8-00c7ae653a1f.png)

**Comment by Zeta-qixi** [comment]
因为master不一定是群主或管理，如果要使用，要在env.dev设置master。或者你把后面master判定删掉也行。

**Comment by Fui-Reconk** [comment]
这样的话群主管理和master就不能用了啊...

**Comment by Zeta-qixi** [comment]
啊 这里写错了 感谢反馈。 直接用添加关注的判定改过去就好。
