### ISSUE TITLE
关于提醒clock插件

### ISSUE THREAD

**Issue by liuzj288** [Zeta-qixi/nonebot2-plugins#11]
1.目前只有master账号能添加提醒呢，怎么增加权限，比如增加群主和管理员，甚至所有群员均可设置，

2.而且消息怎么设置可以@自己或者全体？普通消息容易忽略

3.怎么指定日期呢？比如只需要2月1日0:00这一次提醒怎么设置

**Comment by Zeta-qixi** [comment]
1.目前添加权限就是是群主 管理员 master帐号，没有动态修改权限，自定义权限可以修改`__init__.py` 119 行。
2.qq的 @某人 最后会有空格， 只需@ 放文本内容最后就好了。（但只能@一个主体）
3.数据库格式支持日期，我自己使用是 web+数据库修改的；文本交互方式很麻烦，目前没有修改这个的打算。

**Comment by Zeta-qixi** [comment]
> 1.目前添加权限就是是群主 管理员 master帐号，没有动态修改权限，自定义权限可以修改`__init__.py` 119 行。
> 2.qq的 @某人 最后会有空格， 只需@ 放文本内容最后就好了。（但只能@一个主体）
> 3.数据库格式支持日期，我自己使用是 web+数据库修改的；文本交互方式很麻烦，目前没有修改这个的打算。

3 主要是怎么设计正则，`clock`类也设计好相应接口。如果你有好的想法可以提出。

**Comment by Zeta-qixi** [comment]
已更新功能
