### ISSUE TITLE
rua功能无法使用

### ISSUE THREAD

**Issue by fatinghenji** [Zeta-qixi/nonebot2-plugins#4]
bot报错
![image](https://user-images.githubusercontent.com/37131177/134778325-fe793945-6329-400d-81f8-708a8e638884.png)

**Comment by Zeta-qixi** [comment]
这个功能如果是gif或者过大图片会失败，有空想想合适的代替方案

**Comment by fatinghenji** [comment]
使用的是rua qq号的调用方法
应该不存在图片过大？

**Comment by Zeta-qixi** [comment]
> 使用的是rua qq号的调用方法
> 应该不存在图片过大？

新的代码已经推上去了，但关于gif无法rua的问题还是存在。
rua qq头像可以直接戳一戳，更方便
