### ISSUE TITLE
nb2好像大更了一次

### ISSUE THREAD

**Issue by ID114514** [Zeta-qixi/nonebot2-plugins#5]
emmm估计没法适配新版本

**Comment by Zeta-qixi** [comment]
现在有是b版的分支，部分使用频率少的插件没有迁移

**Comment by ID114514** [comment]
rua好像还是坏的，CQ那边发不出来，消息为空......

**Comment by Zeta-qixi** [comment]
用什么触发的？

**Comment by ID114514** [comment]
找到原因了，rua.py中24行多打了个斜杠，不过不知道为什么master保护没法生效......

**Comment by Zeta-qixi** [comment]
试试最新的代码

**Comment by ID114514** [comment]
> 试试最新的代码

欧克了，不过要不要考虑下戳bot时不自动rua机器人

**Comment by Zeta-qixi** [comment]
可以在`rua.py`文件 32 行的 `_t3`方法内加入下面代码 终止触发
```
if event.target_id == int(bot.self_id):
  return
```

**Comment by ID114514** [comment]
> 可以在`rua.py`文件 32 行的 `_t3`方法内加入下面代码 终止触发
> 
> ```
> if event.target_id == int(bot.self_id):
>   return
> ```

欧克，不过那个CQ转码好像还没修，rua.py 中第24行img = MessageSegment.image(f'file://{img_src}')
多了个/ ，删除就正常了

**Comment by Zeta-qixi** [comment]
可能是不同版本python的path方法问题，实际上我两个服务器都不用这么做
