### ISSUE TITLE
请问如何将插件拿出来单独使用

### ISSUE THREAD

**Issue by March7online** [Zeta-qixi/nonebot2-plugins#6]

**Comment by Zeta-qixi** [comment]
如果你知道nonebot的自定义插件目录设置，只需要把想使用的文件这个放进去就好。
可能会存在某些库不存在的报错信息，只需对应的`pip install`即可

**Comment by March7online** [comment]
> 如果你知道nonebot的自定义插件目录设置，只需要把想使用的文件这个放进去就好。 可能会存在某些库不存在的报错信息，只需对应的即可`pip install`

@A@这个真的不知道，之前装插件都是直接在PowerShell里输入指令

**Comment by Zeta-qixi** [comment]
一般是在bot.py 同级的 src/plugins 下，具体看生成bot时 命令行的选择

**Comment by March7online** [comment]
> 一般是在 bot.py 同级的 src/plugins 下，具体看生成bot时 命令行的选择

所以我只需要把其中插件中的其中一个单独拿出来放到src/plugins里就可以了是吗

**Comment by Zeta-qixi** [comment]
嗯。 如果加载成功，在启动时 能在命令行看到插件名字

**Comment by March7online** [comment]
> 嗯。如果加载成功，在启动时 能在命令行看到插件名字

已经加载成功了，谢谢你的耐心指导

**Comment by March7online** [comment]
> 嗯。如果加载成功，在启动时 能在命令行看到插件名字

@A@ 现在又出现了新的问题，可以麻烦你再看一下吗
![image](https://user-images.githubusercontent.com/93416761/161900962-d667a44f-fb09-41ea-a176-93ed1041698e.png)
![image](https://user-images.githubusercontent.com/93416761/161901027-10c5b224-7630-4e0f-9797-d94cf49e2cda.png)

**Comment by Zeta-qixi** [comment]
截图报错信息

**Comment by GilgameshSAMA** [comment]
![image](https://user-images.githubusercontent.com/93416761/161913441-d9e7002b-b7ef-4a8f-a20d-0e662f9f647d.png)
![image](https://user-images.githubusercontent.com/93416761/161913507-91674575-2923-4f7b-b05c-ef0ac3dd1fba.png)
![image](https://user-images.githubusercontent.com/93416761/161913557-acc8b812-bad7-4257-a91c-069f6022893e.png)


> 截图报错信息

**Comment by March7online** [comment]
> 截图报错信息

![image](https://user-images.githubusercontent.com/93416761/161914355-63b5f05d-be5d-4ede-a089-8d380daddd20.png)
它并没有报错

**Comment by Zeta-qixi** [comment]
尝试将 rua.py 24行 参数修改为 `f'file:///{img_src}' `

**Comment by March7online** [comment]
> f'file:///{img_src}'

更改完以后问题解决了
![image](https://user-images.githubusercontent.com/93416761/161914889-4d5dc9d1-59ba-4313-9fa9-c30cada0581f.png)
