### ISSUE TITLE
rua的报错

### ISSUE THREAD

**Issue by jx9468** [Zeta-qixi/nonebot2-plugins#7]
![aa](https://user-images.githubusercontent.com/78193384/161884717-b407c02f-42bc-4891-8337-af988d424d10.png)
请问一下这个是什么原因😭

**Comment by Zeta-qixi** [comment]
这个需要你在nonebot的配置文件`.env,dev`添加
```
MASTER = []
```

或者将文件`rua/run.py`的 16到19行修改为
```

master = []

```

**Comment by jx9468** [comment]
> 
![vvbb](https://user-images.githubusercontent.com/78193384/161888494-5a812af8-7154-4a96-a525-e60e8332b351.png)


我以为会自动调用env的SUPERUSERS，但还是有问题😂

**Comment by Zeta-qixi** [comment]
因为superuser是string..
还有什么问题，是不是消息为空？

**Comment by jx9468** [comment]
> 因为超级用户是字符串.. 还有什么问题，是不是消息为空？

嗯，go—cqhttp消息为空

**Comment by Zeta-qixi** [comment]
参考
https://github.com/Zeta-qixi/nonebot2-plugins/issues/5

**Comment by jx9468** [comment]
> 参考 #5

![image](https://user-images.githubusercontent.com/78193384/161891207-9800d193-d7aa-47e2-bdde-5d6f73dd1f17.png)
24行的那个斜杠好像不影响，有无那个斜杠只是go端的报错file后有无一个/的区别

**Comment by jx9468** [comment]
![image](https://user-images.githubusercontent.com/78193384/161891747-85678440-4ad1-434d-8365-3e1eb8519a72.png)
这一段的斜杠问题吗，双杠和单杠混在一起

**Comment by Zeta-qixi** [comment]
24行方法的参数 要绝对路径，比如 `file:///C:\\Users\Richard\Pictures\1.png`。
或许你可以直接写绝对路径试试

**Comment by Zeta-qixi** [comment]
24行的参数 就是go的这个file

**Comment by Zeta-qixi** [comment]
你这里好像是win的`os.path.dirname(__file__)`方法没有获取到绝对路径

**Comment by jx9468** [comment]
![image](https://user-images.githubusercontent.com/78193384/161896196-30436fb8-3c65-4ac3-8782-646e7b7977b5.png)
不知道为什么会全都加一条杠

**Comment by Zeta-qixi** [comment]
win默认是`\` 在python里使用需要转义，所以是`\\` 。
你可以把`\`改为`\\`或`/`

**Comment by jx9468** [comment]
> win默认是`\` 在python里使用需要转义，所以是`\\` 。 你可以把`\`改为`\\`或`/`

谢谢，绝对路径可以使用
