### ISSUE TITLE
我将bilibli这个插件放到我的NoeBot2机器人插件目录后启动发生问题

### ISSUE THREAD

**Issue by Arturia169** [Zeta-qixi/nonebot2-plugins#8]
报错如下
![image](https://user-images.githubusercontent.com/69199123/169493421-9aa883c0-fcf1-412f-88af-6111a92ec765.png)
![image](https://user-images.githubusercontent.com/69199123/169493493-9187e245-4cd0-438f-bad0-4bdc9acc5b62.png)

**Comment by Zeta-qixi** [comment]
可以的话，截图看一下bot的目录结构，这个报错和插件关系不大。（近期会优化更新这个插件，当然目前也是能用的）

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/169553644-ec0be83d-a798-40e3-9e52-377de9723075.png)

**Comment by Zeta-qixi** [comment]
啊 把插件那个目录展开看看

**Comment by Arturia169** [comment]
插件由于出错我已经删了，目前文件夹是空的路径 src/plugin

**Comment by Zeta-qixi** [comment]
这可能插件目录设置，或位置放错的问题。如果是插件加载报错应该是`Failed to import bilibili`， 而不是`live`。
是不是没有把`bilibili`整个文件放进去，而把里面的文件直接放到plugins中。

**Comment by Zeta-qixi** [comment]
新版本已上传，试试整个`bilibili`文件夹放到插件文件夹下
